# Generated by Django 6.0.6 on 2026-06-20 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('address', models.TextField(verbose_name='Адрес проживания')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('registered', 'На учёте'), ('exempt', 'Освобождён'), ('serving', 'В армии'), ('reserve', 'В запасе')], default='registered', max_length=20, verbose_name='Статус призыва')),
            ],
            options={
                'verbose_name': 'Призывник',
                'verbose_name_plural': 'Призывники',
            },
        ),
        migrations.CreateModel(
            name='DraftCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название кампании')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('conscripts', models.ManyToManyField(related_name='campaigns', to='voenkomat.conscript', verbose_name='Призывники')),
            ],
            options={
                'verbose_name': 'Призывная кампания',
                'verbose_name_plural': 'Призывные кампании',
            },
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_category', models.CharField(max_length=10, verbose_name='Категория годности')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('conscript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='voenkomat.conscript', verbose_name='Призывник')),
            ],
            options={
                'verbose_name': 'Медицинские данные',
                'verbose_name_plural': 'Медицинские данные',
            },
        ),
    ]
